# Generated by Django 5.1.3 on 2024-12-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
