# Generated by Django 5.1.3 on 2024-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='rating_count',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (2, 'three'), (4, 'four'), (5, 'five')]),
        ),
    ]
